#!/bin/python

import urllib.request, json

city = "Chicago, US"
api_key = "74724628d56eecdeefe03d2483350c91"
units = "Imperial"
unit_key = "F"

weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?q={}&APPID={}&units={}".format(city, api_key, units)).read())[2:-1])

info = weather["weather"][0]["description"].capitalize()
temp = int(float(weather["main"]["temp"]))

# Old output
# print("%s, %i °%s" % (info, temp, unit_key))

print("%i°%s" % (temp, unit_key))
